---
- name: Configure the golden image
  hosts: default
  become: true

  pre_tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

  vars_files:
    - ./vars.yml
    
  roles:
    - initial_setup
    # - install_docker
    - netplan_setup